# Generated by Django 5.1.4 on 2024-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pswd', models.TextField()),
                ('shipping_address', models.TextField()),
                ('phone_number', models.TextField()),
                ('card_number', models.IntegerField()),
                ('card_type', models.CharField(choices=[('pending', 'Pending'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('wema', 'Wema')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
