# Generated by Django 5.1.4 on 2024-12-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
